import Fastify, { FastifyRequest, FastifyReply } from 'fastify';
import cookie from '@fastify/cookie';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import argon2 from 'argon2';
import crypto from 'node:crypto';
import { Pool } from 'pg';
import Redis from 'ioredis';
import { z } from 'zod';


const env = z.object({
  NODE_ENV:z.string().default('development'), DATABASE_URL:z.string(), JWT_SECRET:z.string().min(32),
  COOKIE_SECRET:z.string().min(32), WEB_ORIGIN:z.string(), API_PORT:z.coerce.number().default(4000),
  WINGS_SHARED_SECRET:z.string().min(16), NODE_ENCRYPTION_KEY:z.string().min(32).default('jz-development-node-encryption-key-32'), JZ_BOOTSTRAP_TOKEN:z.string().min(16).optional(),
  ADMIN_USERNAME:z.string().regex(/^[a-zA-Z0-9_.-]{3,32}$/).optional(), ADMIN_EMAIL:z.string().email().optional(), ADMIN_PASSWORD:z.string().min(12).max(256).optional(),
}).parse(process.env);
const db = new Pool({connectionString:env.DATABASE_URL,max:20,ssl:process.env.DATABASE_SSL==='true'?{rejectUnauthorized:process.env.DATABASE_SSL_REJECT_UNAUTHORIZED!=='false'}:undefined});
const app = Fastify({logger:true,genReqId:()=>crypto.randomUUID(),trustProxy:true});

declare module 'fastify' { interface FastifyRequest { user?: {id:string;role:string;permissions:string[]}; } }

await app.register(helmet);
await app.register(cookie,{secret:env.COOKIE_SECRET,hook:'onRequest'});
await app.register(cors,{origin:env.WEB_ORIGIN,credentials:true});
await app.register(rateLimit,{max:120,timeWindow:'1 minute'});
app.addHook('onRequest',async(req,reply)=>reply.header('x-request-id',req.id));

const hash=(s:string)=>crypto.createHash('sha256').update(s).digest('hex');
const aesKey=crypto.createHash('sha256').update(env.NODE_ENCRYPTION_KEY).digest();
function encrypt(value:string){const iv=crypto.randomBytes(12);const c=crypto.createCipheriv('aes-256-gcm',aesKey,iv);const data=Buffer.concat([c.update(value,'utf8'),c.final()]);return `${iv.toString('base64url')}.${c.getAuthTag().toString('base64url')}.${data.toString('base64url')}`;}
function decrypt(value:string){const [iv,tag,data]=value.split('.');const d=crypto.createDecipheriv('aes-256-gcm',aesKey,Buffer.from(iv,'base64url'));d.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([d.update(Buffer.from(data,'base64url')),d.final()]).toString('utf8');}
function clientIp(req:FastifyRequest){return (req.headers['x-forwarded-for']?.toString().split(',')[0]||req.ip).slice(0,64);}
async function audit(req:FastifyRequest,action:string,targetType:string,targetId:string|null,result:string,metadata:any={}){await db.query('insert into activity_logs(user_id,action,target_type,target_id,result,ip,request_id,metadata) values($1,$2,$3,$4,$5,$6,$7,$8)',[req.user?.id||null,action,targetType,targetId,result,clientIp(req),req.id,metadata]);}
async function enqueue(job:any){if(!process.env.REDIS_URL)return;const r = new Redis(process.env.REDIS_URL);await r.lpush('jz:jobs',JSON.stringify(job));await r.quit();}
async function wingsRequest(nodeId:string,path:string,method='GET',payload:any=undefined){const q=await db.query('select n.address,nc.secret_encrypted from nodes n join node_credentials nc on nc.node_id=n.id where n.id=$1',[nodeId]);if(!q.rows[0])throw Object.assign(new Error('NODE_NOT_FOUND'),{statusCode:404});const base=q.rows[0].address.replace(/\/$/,'');const body=payload===undefined?'':JSON.stringify(payload);const ts=Math.floor(Date.now()/1000).toString();const material=`${ts}\n${method}\n${path}\n${hash(body)}`;const sig=crypto.createHmac('sha256',decrypt(q.rows[0].secret_encrypted)).update(material).digest('hex');const r=await fetch(`${base}${path}`,{method,headers:{'content-type':'application/json','x-jz-timestamp':ts,'x-jz-signature':sig,'x-jz-node-id':nodeId},body:body||undefined});const text=await r.text();let data:any;try{data=JSON.parse(text)}catch{data={raw:text}}if(!r.ok)throw Object.assign(new Error(data.error||data.raw||'WINGS_REQUEST_FAILED'),{statusCode:r.status});return data;}
async function serverForUser(req:FastifyRequest,id:string){const q=await db.query('select s.*,n.address from servers s join nodes n on n.id=s.node_id where s.id=$1',[id]);if(!q.rows[0])return null;const s=q.rows[0];if(req.user!.role!=='Super Administrator'&&!req.user!.permissions.includes('servers.view')&&s.owner_id!==req.user!.id)throw Object.assign(new Error('FORBIDDEN'),{statusCode:403});if(req.user!.role!=='Super Administrator'&&s.owner_id!==req.user!.id&&!req.user!.permissions.includes('servers.update'))throw Object.assign(new Error('FORBIDDEN'),{statusCode:403});return s;}
async function ensureBootstrapAdmin(){const username=process.env.ADMIN_USERNAME?.toLowerCase(),email=process.env.ADMIN_EMAIL?.toLowerCase(),password=process.env.ADMIN_PASSWORD;if(!username||!email||!password)return;const passwordHash=await argon2.hash(password,{type:argon2.argon2id,memoryCost:65536,timeCost:3,parallelism:1});const c=await db.connect();try{await c.query('begin');const r=await c.query('select id from users where email=$1 or username=$2 limit 1',[email,username]);let id:string;if(r.rows[0]){id=r.rows[0].id;await c.query('update users set username=$1,email=$2,password_hash=$3,updated_at=now() where id=$4',[username,email,passwordHash,id]);}else{const u=await c.query('insert into users(username,email,password_hash) values($1,$2,$3) returning id',[username,email,passwordHash]);id=u.rows[0].id;}const role=await c.query("select id from roles where name='Administrator' limit 1");if(role.rows[0])await c.query('insert into user_roles(user_id,role_id) values($1,$2) on conflict do nothing',[id,role.rows[0].id]);await c.query('commit');}catch(e){await c.query('rollback');throw e;}finally{c.release();}}

async function requireAuth(req:FastifyRequest,reply:FastifyReply){
  const sid=req.cookies.jz_session;if(!sid)return reply.code(401).send({error:'UNAUTHENTICATED'});
  const {rows}=await db.query(`select s.user_id,u.username,coalesce(string_agg(distinct r.name,','),'User') roles
    from sessions s join users u on u.id=s.user_id left join user_roles ur on ur.user_id=u.id left join roles r on r.id=ur.role_id
    where s.token_hash=$1 and s.expires_at>now() and u.disabled_at is null group by s.user_id,u.username limit 1`,[hash(sid)]);
  if(!rows[0])return reply.code(401).send({error:'UNAUTHENTICATED'});
  const perms=await db.query(`select distinct p.name from permissions p join role_permissions rp on rp.permission_id=p.id join user_roles ur on ur.role_id=rp.role_id where ur.user_id=$1`,[rows[0].user_id]);
  req.user={id:rows[0].user_id,role:rows[0].roles.split(',')[0]||'User',permissions:perms.rows.map((x:any)=>x.name)}; await db.query('update sessions set last_seen_at=now() where token_hash=$1',[hash(sid)]);
}
function requirePermission(permission:string){return async(req:FastifyRequest,reply:FastifyReply)=>{await requireAuth(req,reply);if(reply.sent)return;if(req.user?.role==='Super Administrator')return;if(!req.user?.permissions.includes(permission))return reply.code(403).send({error:'FORBIDDEN',permission});};}
function parseBody<T extends z.ZodTypeAny>(schema:T,req:FastifyRequest,reply:FastifyReply):z.infer<T>|undefined{const r=schema.safeParse(req.body);if(!r.success){reply.code(400).send({error:'VALIDATION_ERROR',details:r.error.issues});return;}return r.data;}

app.get('/api/health',async()=>({ok:true,service:'jz-api',version:'0.8.0',time:new Date().toISOString()}));
app.get('/api/ready',async()=>{const checks:any={database:false,redis:!!process.env.REDIS_URL};try{await db.query('select 1');checks.database=true;}catch{}return {ok:checks.database,checks};});

const registerSchema=z.object({username:z.string().regex(/^[a-zA-Z0-9_.-]{3,32}$/),email:z.string().email().max(254),password:z.string().min(12).max(256),confirmPassword:z.string()});
app.post('/api/auth/register',async(req,reply)=>{const b=parseBody(registerSchema,req,reply);if(!b)return;if(b.password!==b.confirmPassword)return reply.code(400).send({error:'PASSWORD_MISMATCH'});const passwordHash=await argon2.hash(b.password,{type:argon2.argon2id,memoryCost:65536,timeCost:3,parallelism:1});const c=await db.connect();try{await c.query('begin');const u=await c.query('insert into users(username,email,password_hash) values($1,$2,$3) returning id,username,email',[b.username.toLowerCase(),b.email.toLowerCase(),passwordHash]);await c.query("insert into user_roles(user_id,role_id) select $1,id from roles where name='User'",[u.rows[0].id]);await c.query('commit');return reply.code(201).send({user:u.rows[0]});}catch(e:any){await c.query('rollback');if(e.code==='23505')return reply.code(409).send({error:'ACCOUNT_ALREADY_EXISTS'});throw e;}finally{c.release();}});

const loginSchema=z.object({identifier:z.string().min(3).max(254),password:z.string().min(1).max(256),remember:z.boolean().optional()});
app.post('/api/auth/login',async(req,reply)=>{const b=parseBody(loginSchema,req,reply);if(!b)return;const {rows}=await db.query('select u.id,u.username,u.password_hash,coalesce(r.name,\'User\') role from users u left join user_roles ur on ur.user_id=u.id left join roles r on r.id=ur.role_id where u.email=$1 or u.username=$1 limit 1',[b.identifier.toLowerCase()]);const ok=!!rows[0]&&await argon2.verify(rows[0].password_hash,b.password).catch(()=>false);await db.query('insert into login_events(user_id,identifier,success,ip,user_agent) values($1,$2,$3,$4,$5)',[rows[0]?.id||null,b.identifier,ok,clientIp(req),req.headers['user-agent']?.slice(0,512)||null]);if(!ok)return reply.code(401).send({error:'INVALID_CREDENTIALS'});const raw=crypto.randomBytes(48).toString('base64url');const ttl=b.remember?'30 days':'12 hours';await db.query(`insert into sessions(user_id,token_hash,expires_at) values($1,$2,now()+$3::interval)`,[rows[0].id,hash(raw),ttl]);reply.setCookie('jz_session',raw,{httpOnly:true,secure:env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:b.remember?2592000:43200});return {user:{id:rows[0].id,username:rows[0].username,role:rows[0].role}};});
app.post('/api/auth/logout',{preHandler:requireAuth},async(req,reply)=>{await db.query('delete from sessions where token_hash=$1',[hash(req.cookies.jz_session!)]);reply.clearCookie('jz_session',{path:'/'});return {ok:true};});
app.get('/api/me',{preHandler:requireAuth},async(req)=>{const {rows}=await db.query('select id,username,email,email_verified_at,created_at from users where id=$1',[req.user!.id]);return {...rows[0],role:req.user!.role,permissions:req.user!.permissions};});
app.get('/api/me/sessions',{preHandler:requireAuth},async(req)=>{const {rows}=await db.query('select id,created_at,expires_at from sessions where user_id=$1 order by created_at desc',[req.user!.id]);return rows;});
app.delete('/api/me/sessions/:id',{preHandler:requireAuth},async(req)=>{await db.query('delete from sessions where id=$1 and user_id=$2',[(req.params as any).id,req.user!.id]);return {ok:true};});

const usernameSchema=z.object({username:z.string().regex(/^[a-zA-Z0-9_.-]{3,32}$/)});
app.patch('/api/me/username',{preHandler:requireAuth},async(req,reply)=>{const b=parseBody(usernameSchema,req,reply);if(!b)return;try{const r=await db.query('update users set username=$1,updated_at=now() where id=$2 returning id,username,email',[b.username.toLowerCase(),req.user!.id]);if(!r.rows[0])return reply.code(404).send({error:'USER_NOT_FOUND'});await audit(req,'user.username.update','user',req.user!.id,'success');return r.rows[0];}catch(e:any){if(e.code==='23505')return reply.code(409).send({error:'USERNAME_ALREADY_EXISTS'});throw e;}});
const passwordChangeSchema=z.object({currentPassword:z.string().min(1).max(256),newPassword:z.string().min(12).max(256),confirmPassword:z.string()});
app.post('/api/me/password',{preHandler:requireAuth},async(req,reply)=>{const b=parseBody(passwordChangeSchema,req,reply);if(!b)return;if(b.newPassword!==b.confirmPassword)return reply.code(400).send({error:'PASSWORD_MISMATCH'});const r=await db.query('select password_hash from users where id=$1',[req.user!.id]);if(!r.rows[0]||!(await argon2.verify(r.rows[0].password_hash,b.currentPassword).catch(()=>false)))return reply.code(401).send({error:'CURRENT_PASSWORD_INVALID'});const next=await argon2.hash(b.newPassword,{type:argon2.argon2id,memoryCost:65536,timeCost:3,parallelism:1});await db.query('update users set password_hash=$1,updated_at=now() where id=$2',[next,req.user!.id]);await db.query('delete from sessions where user_id=$1',[req.user!.id]);await audit(req,'user.password.update','user',req.user!.id,'success');return {ok:true,reauthentication_required:true};});
app.get('/api/dashboard',{preHandler:requireAuth},async(req)=>{const [nodes,servers,activity]=await Promise.all([db.query('select id,name,status,address,location,cpu_percent,ram_used_bytes,ram_total_bytes,disk_used_bytes,disk_total_bytes,last_heartbeat,wings_version,docker_version from nodes order by name'),db.query('select s.id,s.name,s.status,s.cpu_limit,s.memory_limit,s.disk_limit,s.node_id,n.name node_name,s.primary_allocation_id,a.ip,a.port from servers s join nodes n on n.id=s.node_id left join allocations a on a.id=s.primary_allocation_id where s.owner_id=$1 order by s.created_at desc',[req.user!.id]),db.query('select action,target_type,target_id,result,created_at from activity_logs where user_id=$1 order by created_at desc limit 10',[req.user!.id])]);return {nodes:nodes.rows,servers:servers.rows,activity:activity.rows};});

app.get('/api/admin/stats',{preHandler:requirePermission('system.view')},async()=>{const q=await db.query(`select (select count(*) from users) users,(select count(*) from nodes) nodes,(select count(*) from nodes where status='ONLINE') online_nodes,(select count(*) from servers) servers,(select count(*) from servers where status='RUNNING') running_servers`);return q.rows[0];});
app.post('/api/bootstrap/local-node',async(req,reply)=>{const supplied=req.headers['x-jz-bootstrap-token']?.toString();if(!env.JZ_BOOTSTRAP_TOKEN||!supplied||Buffer.byteLength(supplied)!==Buffer.byteLength(env.JZ_BOOTSTRAP_TOKEN)||!crypto.timingSafeEqual(Buffer.from(supplied),Buffer.from(env.JZ_BOOTSTRAP_TOKEN)))return reply.code(403).send({error:'BOOTSTRAP_FORBIDDEN'});const b=parseBody(z.object({name:z.string().min(2).max(64),address:z.string().min(3).max(255),location:z.string().max(64).optional()}),req,reply);if(!b)return;const secret=crypto.randomBytes(32).toString('base64url');const c=await db.connect();try{await c.query('begin');const n=await c.query("insert into nodes(name,address,location,status) values($1,$2,$3,'CONNECTING') on conflict(name) do update set address=excluded.address,location=excluded.location returning id,name,address,location,status",[b.name,b.address,b.location||null]);await c.query('insert into node_credentials(node_id,secret_hash,secret_encrypted) values($1,$2,$3) on conflict(node_id) do update set secret_hash=excluded.secret_hash,secret_encrypted=excluded.secret_encrypted',[n.rows[0].id,hash(secret),encrypt(secret)]);await c.query('commit');return {node:n.rows[0],secret};}catch(e){await c.query('rollback');throw e;}finally{c.release();}});


app.get('/api/deployment/targets',{preHandler:requirePermission('nodes.view')},async()=>{
  const {rows}=await db.query("select id,name,kind,enabled,config,created_at,updated_at from deployment_targets order by case kind when 'VPS' then 1 when 'CODESANDBOX' then 2 when 'PLAYIT' then 3 else 9 end,name");
  return rows.map((x:any)=>({id:x.id,name:x.name,kind:x.kind,enabled:x.enabled,config:{description:x.config?.description||null,public_url_base:x.config?.public_url_base||null,public_url_template:x.config?.public_url_template||null,port_range:x.config?.port_range||null},created_at:x.created_at,updated_at:x.updated_at}));
});
const deploymentTargetSchema=z.object({name:z.string().min(2).max(80),kind:z.enum(['VPS','CODESANDBOX','PLAYIT']),enabled:z.boolean().optional(),config:z.record(z.any()).optional()});
app.put('/api/deployment/targets/:id',{preHandler:requirePermission('system.settings')},async(req,reply)=>{
  const b=parseBody(deploymentTargetSchema,req,reply);if(!b)return;
  const r=await db.query('update deployment_targets set name=$1,kind=$2,enabled=coalesce($3,enabled),config=$4,updated_at=now() where id=$5 returning id,name,kind,enabled,config,updated_at',[b.name,b.kind,b.enabled??true,JSON.stringify(b.config||{}),(req.params as any).id]);
  if(!r.rows[0])return reply.code(404).send({error:'DEPLOYMENT_TARGET_NOT_FOUND'});await audit(req,'deployment.target.updated','deployment_target',r.rows[0].id,'success');return r.rows[0];
});
app.post('/api/deployment/targets/:id/allocate-port',{preHandler:requirePermission('nodes.update')},async(req,reply)=>{
  const targetId=(req.params as any).id;
  const target=await db.query('select * from deployment_targets where id=$1 and enabled=true',[targetId]);
  if(!target.rows[0])return reply.code(404).send({error:'DEPLOYMENT_TARGET_NOT_FOUND'});
  const cfg=target.rows[0].config||{};const range=cfg.port_range||[3000,3999];const low=Math.max(1,Number(range[0]||3000)),high=Math.min(65535,Number(range[1]||3999));
  const c=await db.connect();try{await c.query('begin');
    const free=await c.query('select p from generate_series($1,$2) p where not exists(select 1 from deployment_ports d where d.target_id=$3 and d.port=p) order by p limit 1',[low,high,targetId]);
    if(!free.rows[0])throw Object.assign(new Error('NO_PORT_AVAILABLE'),{statusCode:409});
    const port=Number(free.rows[0].p);await c.query("insert into deployment_ports(target_id,port,status) values($1,$2,'RESERVED')",[targetId,port]);await c.query('commit');
    let address:string|null=null;const base=typeof cfg.public_url_base==='string'?cfg.public_url_base.replace(/\/$/,''):null;const template=typeof cfg.public_url_template==='string'?cfg.public_url_template:null;
    if(template)address=template.replaceAll('{port}',String(port));else if(base)address=`${base}:${port}`;
    await audit(req,'deployment.port.reserved','deployment_target',targetId,'success',{port,kind:target.rows[0].kind});
    return {ok:true,target:{id:target.rows[0].id,name:target.rows[0].name,kind:target.rows[0].kind},port,public_address:address,requires_provider_configuration:!address};
  }catch(e:any){await c.query('rollback');if(e.statusCode)return reply.code(e.statusCode).send({error:e.message});throw e;}finally{c.release();}
});
app.get('/api/deployment/ports',{preHandler:requirePermission('nodes.view')},async()=>{const {rows}=await db.query("select p.id,p.port,p.status,p.public_address,p.created_at,t.name target_name,t.kind,s.name server_name from deployment_ports p join deployment_targets t on t.id=p.target_id left join servers s on s.id=p.server_id order by t.name,p.port");return rows;});

app.get('/api/nodes',{preHandler:requirePermission('nodes.view')},async()=>{const {rows}=await db.query('select id,name,address,location,status,wings_version,docker_version,cpu_percent,ram_used_bytes,ram_total_bytes,disk_used_bytes,disk_total_bytes,last_heartbeat,last_error,maintenance_reason from nodes order by created_at desc');return rows;});
const nodeSchema=z.object({name:z.string().min(2).max(64),address:z.string().min(3).max(255),location:z.string().max(64).optional()});
app.post('/api/nodes',{preHandler:requirePermission('nodes.create')},async(req,reply)=>{const b=parseBody(nodeSchema,req,reply);if(!b)return;const secret=crypto.randomBytes(32).toString('base64url');const c=await db.connect();try{await c.query('begin');const n=await c.query('insert into nodes(name,address,location,status) values($1,$2,$3,\'CONNECTING\') returning id,name,address,location,status',[b.name,b.address,b.location||null]);await c.query('insert into node_credentials(node_id,secret_hash,secret_encrypted) values($1,$2,$3)',[n.rows[0].id,hash(secret),encrypt(secret)]);await c.query('commit');await audit(req,'node.created','node',n.rows[0].id,'success');return reply.code(201).send({node:n.rows[0],secret});}catch(e){await c.query('rollback');throw e;}finally{c.release();}});
app.post('/api/nodes/:id/credentials/rotate',{preHandler:requirePermission('nodes.update')},async(req,reply)=>{const id=(req.params as any).id;const secret=crypto.randomBytes(32).toString('base64url');const r=await db.query('update node_credentials set secret_hash=$1,secret_encrypted=$2 where node_id=$3',[hash(secret),encrypt(secret),id]);if(!r.rowCount)return reply.code(404).send({error:'NODE_NOT_FOUND'});await audit(req,'node.credentials.rotate','node',id,'success');return {secret};});
app.post('/api/nodes/:id/action',{preHandler:requirePermission('nodes.update')},async(req,reply)=>{const id=(req.params as any).id;const b=parseBody(z.object({action:z.enum(['enable','disable','maintenance'])}),req,reply);if(!b)return;const status=b.action==='maintenance'?'MAINTENANCE':b.action==='disable'?'DISABLED':'CONNECTING';await db.query('update nodes set status=$1,maintenance_reason=$2 where id=$3',[status,b.action==='maintenance'?'Maintenance requested':null,id]);await audit(req,`node.${b.action}`,'node',id,'success');return {ok:true,status};});

app.get('/api/servers',{preHandler:requirePermission('servers.view')},async(req)=>{const admin=req.user!.role==='Super Administrator'||req.user!.permissions.includes('users.view');const {rows}=await db.query(`select s.*,n.name node_name,a.ip,a.port,e.name egg_name,ev.version egg_version from servers s join nodes n on n.id=s.node_id left join allocations a on a.id=s.primary_allocation_id left join egg_versions ev on ev.id=s.egg_version_id left join eggs e on e.id=ev.egg_id ${admin?'':'where s.owner_id=$1'} order by s.created_at desc`,admin?[]:[req.user!.id]);return rows;});
const serverCreateSchema=z.object({owner_id:z.string().uuid(),name:z.string().min(1).max(80),node_id:z.string().uuid(),egg_version_id:z.string().uuid().optional(),allocation_id:z.string().uuid().optional(),cpu_limit:z.number().int().positive().max(100000),memory_limit:z.number().int().positive(),disk_limit:z.number().int().positive(),image:z.string().max(255).optional(),startup_command:z.string().max(2000).optional(),auto_start:z.boolean().optional()});
app.post('/api/servers',{preHandler:requirePermission('servers.create')},async(req,reply)=>{const b=parseBody(serverCreateSchema,req,reply);if(!b)return;const c=await db.connect();let id='';try{await c.query('begin');const n=await c.query('select id,status from nodes where id=$1 for update',[b.node_id]);if(!n.rows[0])throw Object.assign(new Error('NODE_NOT_FOUND'),{statusCode:404});if(['OFFLINE','DISABLED'].includes(n.rows[0].status))throw Object.assign(new Error('NODE_UNAVAILABLE'),{statusCode:409});if(b.allocation_id){const a=await c.query('select id,server_id from allocations where id=$1 and node_id=$2 for update',[b.allocation_id,b.node_id]);if(!a.rows[0])throw Object.assign(new Error('ALLOCATION_NOT_FOUND'),{statusCode:404});if(a.rows[0].server_id)throw Object.assign(new Error('ALLOCATION_BUSY'),{statusCode:409});}const s=await c.query(`insert into servers(owner_id,name,node_id,egg_version_id,primary_allocation_id,cpu_limit,memory_limit,disk_limit,image,startup_command,auto_start,status) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'INSTALLING') returning *`,[b.owner_id,b.name,b.node_id,b.egg_version_id||null,b.allocation_id||null,b.cpu_limit,b.memory_limit,b.disk_limit,b.image||'ubuntu:24.04',b.startup_command||'/bin/sh',!!b.auto_start]);id=s.rows[0].id;if(b.allocation_id)await c.query('update allocations set server_id=$1,primary_for_server=true where id=$2',[id,b.allocation_id]);await c.query('insert into server_events(server_id,type,payload) values($1,\'created\',$2)',[id,JSON.stringify({by:req.user!.id})]);await c.query('commit');await enqueue({id:crypto.randomUUID(),type:'server.install',server_id:id,node_id:b.node_id,requested_by:req.user!.id});await audit(req,'server.created','server',id,'success');return reply.code(201).send({server:s.rows[0]});}catch(e:any){await c.query('rollback');if(e.statusCode)return reply.code(e.statusCode).send({error:e.message});throw e;}finally{c.release();}});

async function serverAction(req:FastifyRequest,reply:FastifyReply,action:string){const id=(req.params as any).id;const row=await db.query('select s.id,s.owner_id,s.node_id,s.container_id,n.address from servers s join nodes n on n.id=s.node_id where s.id=$1',[id]);if(!row.rows[0])return reply.code(404).send({error:'SERVER_NOT_FOUND'});const s=row.rows[0];if(req.user!.role!=='Super Administrator'&&!req.user!.permissions.includes(`servers.${action}`)&&s.owner_id!==req.user!.id)return reply.code(403).send({error:'FORBIDDEN'});const job={id:crypto.randomUUID(),type:`server.${action}`,server_id:id,node_id:s.node_id,container_id:s.container_id||null,requested_by:req.user!.id};await enqueue(job);await db.query('update servers set status=$1,updated_at=now() where id=$2',[action==='start'?'STARTING':action==='stop'?'STOPPING':action==='restart'?'RESTARTING':action==='kill'?'STOPPING':'INSTALLING',id]);await db.query('insert into server_events(server_id,type,payload) values($1,$2,$3)',[id,`requested.${action}`,JSON.stringify({job_id:job.id,user_id:req.user!.id})]);await audit(req,`server.${action}`,'server',id,'queued',{job_id:job.id});return {ok:true,job_id:job.id,status:'QUEUED'};}
for(const action of ['start','stop','restart','kill','reinstall'] as const)app.post(`/api/servers/:id/${action}`,{preHandler:requireAuth},async(req,reply)=>serverAction(req,reply,action));
app.get('/api/servers/:id/events',{preHandler:requirePermission('servers.view')},async(req)=>{const {rows}=await db.query('select * from server_events where server_id=$1 order by created_at desc limit 100',[(req.params as any).id]);return rows;});
app.get('/api/servers/:id/logs',{preHandler:requireAuth},async(req,reply)=>{const s=await serverForUser(req,(req.params as any).id);if(!s)return reply.code(404).send({error:'SERVER_NOT_FOUND'});if(!s.container_id)return {logs:'',status:s.status};try{return await wingsRequest(s.node_id,`/v1/servers/${s.container_id}/logs`);}catch(e:any){return reply.code(e.statusCode||502).send({error:e.message});}});
app.post('/api/servers/:id/command',{preHandler:requireAuth},async(req,reply)=>{const s=await serverForUser(req,(req.params as any).id);if(!s)return reply.code(404).send({error:'SERVER_NOT_FOUND'});const b=parseBody(z.object({command:z.string().min(1).max(4000)}),req,reply);if(!b)return;if(!s.container_id)return reply.code(409).send({error:'SERVER_NOT_READY'});try{return await wingsRequest(s.node_id,`/v1/servers/${s.container_id}/command`,'POST',{command:b.command});}catch(e:any){return reply.code(e.statusCode||502).send({error:e.message});}});
app.get('/api/servers/:id/files',{preHandler:requireAuth},async(req,reply)=>{const s=await serverForUser(req,(req.params as any).id);if(!s)return reply.code(404).send({error:'SERVER_NOT_FOUND'});if(!s.container_id)return reply.code(409).send({error:'SERVER_NOT_READY'});const path=String((req.query as any)?.path||'');try{return await wingsRequest(s.node_id,`/v1/servers/${s.container_id}/files-list?path=${encodeURIComponent(path)}`);}catch(e:any){return reply.code(e.statusCode||502).send({error:e.message});}});
app.get('/api/servers/:id/file',{preHandler:requireAuth},async(req,reply)=>{const s=await serverForUser(req,(req.params as any).id);if(!s)return reply.code(404).send({error:'SERVER_NOT_FOUND'});if(!s.container_id)return reply.code(409).send({error:'SERVER_NOT_READY'});const path=String((req.query as any)?.path||'');try{return await wingsRequest(s.node_id,`/v1/servers/${s.container_id}/files-read?path=${encodeURIComponent(path)}`);}catch(e:any){return reply.code(e.statusCode||502).send({error:e.message});}});
app.put('/api/servers/:id/file',{preHandler:requireAuth},async(req,reply)=>{const s=await serverForUser(req,(req.params as any).id);if(!s)return reply.code(404).send({error:'SERVER_NOT_FOUND'});if(!s.container_id)return reply.code(409).send({error:'SERVER_NOT_READY'});const b=parseBody(z.object({path:z.string().max(2048),content:z.string().max(8*1024*1024)}),req,reply);if(!b)return;try{return await wingsRequest(s.node_id,`/v1/servers/${s.container_id}/files-write?path=${encodeURIComponent(b.path)}`,'POST',{content:b.content});}catch(e:any){return reply.code(e.statusCode||502).send({error:e.message});}});
app.post('/api/servers/:id/folder',{preHandler:requireAuth},async(req,reply)=>{const s=await serverForUser(req,(req.params as any).id);if(!s)return reply.code(404).send({error:'SERVER_NOT_FOUND'});if(!s.container_id)return reply.code(409).send({error:'SERVER_NOT_READY'});const b=parseBody(z.object({path:z.string().max(2048)}),req,reply);if(!b)return;try{return await wingsRequest(s.node_id,`/v1/servers/${s.container_id}/files-mkdir?path=${encodeURIComponent(b.path)}`,'POST',{});}catch(e:any){return reply.code(e.statusCode||502).send({error:e.message});}});
app.delete('/api/servers/:id/file',{preHandler:requireAuth},async(req,reply)=>{const s=await serverForUser(req,(req.params as any).id);if(!s)return reply.code(404).send({error:'SERVER_NOT_FOUND'});if(!s.container_id)return reply.code(409).send({error:'SERVER_NOT_READY'});const path=String((req.query as any)?.path||'');try{return await wingsRequest(s.node_id,`/v1/servers/${s.container_id}/files-delete?path=${encodeURIComponent(path)}`,'POST',{});}catch(e:any){return reply.code(e.statusCode||502).send({error:e.message});}});
app.delete('/api/servers/:id',{preHandler:requirePermission('servers.delete')},async(req,reply)=>{const id=(req.params as any).id;const q=await db.query('select id,node_id,container_id,owner_id from servers where id=$1',[id]);if(!q.rows[0])return reply.code(404).send({error:'SERVER_NOT_FOUND'});const s=q.rows[0];if(s.container_id){await enqueue({id:crypto.randomUUID(),type:'server.delete',server_id:id,node_id:s.node_id,container_id:s.container_id,requested_by:req.user!.id});await db.query("update servers set status='DELETING',updated_at=now() where id=$1",[id]);}else await db.query('delete from servers where id=$1',[id]);await audit(req,'server.delete','server',id,'queued');return {ok:true,status:'DELETING'};});

app.get('/api/activity',{preHandler:requirePermission('system.view')},async()=>{const {rows}=await db.query('select * from activity_logs order by created_at desc limit 200');return rows;});
app.get('/api/notifications',{preHandler:requireAuth},async(req)=>{const {rows}=await db.query('select * from notifications where user_id=$1 order by created_at desc limit 100',[req.user!.id]);return rows;});
app.post('/api/notifications/:id/read',{preHandler:requireAuth},async(req)=>{await db.query('update notifications set read_at=now() where id=$1 and user_id=$2',[(req.params as any).id,req.user!.id]);return {ok:true};});

app.get('/api/eggs',{preHandler:requirePermission('servers.view')},async()=>{const {rows}=await db.query('select e.*,count(ev.id)::int version_count from eggs e left join egg_versions ev on ev.egg_id=e.id group by e.id order by e.name');return rows;});
app.get('/api/domains',{preHandler:requirePermission('domains.view')},async()=>{const {rows}=await db.query('select * from domains order by name');return rows;});
app.get('/api/backups',{preHandler:requirePermission('backups.view')},async(req)=>{const admin=req.user!.role==='Super Administrator';const {rows}=await db.query(`select b.* from backups b join servers s on s.id=b.server_id ${admin?'':'where s.owner_id=$1'} order by b.created_at desc limit 200`,admin?[]:[req.user!.id]);return rows;});
app.get('/api/database-hosts',{preHandler:requirePermission('databases.view')},async()=>{const {rows}=await db.query('select id,name,engine,host,port,username,enabled,created_at from database_hosts order by name');return rows;});
app.get('/api/plugins',{preHandler:requirePermission('plugins.view')},async()=>{const {rows}=await db.query('select * from plugin_manifests order by name');return rows;});
app.get('/api/feature-flags',{preHandler:requirePermission('system.settings')},async()=>{const {rows}=await db.query('select * from feature_flags order by key');return rows;});

async function nodeAuth(req:FastifyRequest,reply:FastifyReply){const nodeId=req.headers['x-jz-node-id']?.toString();const ts=req.headers['x-jz-timestamp']?.toString();const sig=req.headers['x-jz-signature']?.toString();if(!nodeId||!ts||!sig)return reply.code(401).send({error:'NODE_AUTH_REQUIRED'});const age=Math.abs(Date.now()/1000-Number(ts));if(!Number.isFinite(age)||age>60)return reply.code(401).send({error:'NODE_AUTH_EXPIRED'});const c=await db.query('select nc.secret_encrypted,nc.secret_hash,n.status from node_credentials nc join nodes n on n.id=nc.node_id where nc.node_id=$1',[nodeId]);if(!c.rows[0]||['DISABLED'].includes(c.rows[0].status))return reply.code(401).send({error:'NODE_NOT_FOUND'});const secret=decrypt(c.rows[0].secret_encrypted);const body=typeof req.body==='string'?req.body:JSON.stringify(req.body||{});const material=`${ts}\n${req.method}\n${req.url}\n${hash(body)}`;const expected=crypto.createHmac('sha256',secret).update(material).digest('hex');if(sig.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return reply.code(401).send({error:'NODE_SIGNATURE_INVALID'});(req as any).nodeId=nodeId;(req as any).nodeStatus=c.rows[0].status;}
app.post('/api/node/v1/heartbeat',{preHandler:nodeAuth},async(req,reply)=>{const b=parseBody(z.object({wings_version:z.string().optional(),docker_version:z.string().optional(),cpu_percent:z.number(),ram_used_bytes:z.number(),ram_total_bytes:z.number(),disk_used_bytes:z.number(),disk_total_bytes:z.number(),running_servers:z.number().int().nonnegative().optional()}),req,reply);if(!b)return;await db.query(`update nodes set status='ONLINE',wings_version=$1,docker_version=$2,cpu_percent=$3,ram_used_bytes=$4,ram_total_bytes=$5,disk_used_bytes=$6,disk_total_bytes=$7,last_heartbeat=now(),last_error=null where id=$8`,[b.wings_version||null,b.docker_version||null,b.cpu_percent,b.ram_used_bytes,b.ram_total_bytes,b.disk_used_bytes,b.disk_total_bytes,(req as any).nodeId]);return {ok:true,server_time:new Date().toISOString()};});
app.post('/api/node/v1/status/:serverId',{preHandler:nodeAuth},async(req,reply)=>{const b=parseBody(z.object({status:z.string(),container_id:z.string().optional(),cpu_percent:z.number().optional(),memory_bytes:z.number().optional(),disk_bytes:z.number().optional()}),req,reply);if(!b)return;await db.query(`update servers set status=$1,container_id=coalesce($2,container_id),updated_at=now() where id=$3 and node_id=$4`,[b.status,b.container_id||null,(req.params as any).serverId,(req as any).nodeId]);await db.query('insert into server_events(server_id,type,payload) values($1,$2,$3)',[(req.params as any).serverId,'status',JSON.stringify(b)]);return {ok:true};});

app.setErrorHandler((err:any,req,reply)=>{req.log.error({err,requestId:req.id},'request failed');if(err instanceof z.ZodError)return reply.code(400).send({error:'VALIDATION_ERROR',details:err.issues});return reply.code(err.statusCode||500).send({error:err.statusCode?err.message:'INTERNAL_ERROR',requestId:req.id});});
await ensureBootstrapAdmin();
await app.listen({port:env.API_PORT,host:'0.0.0.0'});
